#n= list(map(int,input().split()))
#string.split('+',2)
#string.append(input())
#string = string.replace(a, "")
#import re re.sub('[^0-9]', '', string)

print("---------------------------------------")
print("|                                     |")
print("|                                     |")
print("|                                     |")
print("|                                     |")
print("|                                     |")
print("---------------------------------------")
