L = input()

if(L=='A'):
    print("1")
elif(L=='B'):
    print("2")
elif(L=='C'):
    print("3")
elif(L=='D'):
    print("4")
elif(L=='E'):
    print("5")
elif(L=='F'):
    print("6")
elif(L=='G'):
    print("7")
elif(L=='H'):
    print("8")
elif(L=='I'):
    print("9")
elif(L=='J'):
    print("10")
elif(L=='K'):
    print("11")
elif(L=='L'):
    print("12")
elif(L=='M'):
    print("13")
elif(L=='N'):
    print("14")
elif(L=='O'):
    print("15")
elif(L=='P'):
    print("16")
elif(L=='Q'):
    print("17")
elif(L=='R'):
    print("18")
elif(L=='S'):
    print("19")
elif(L=='T'):
    print("20")
elif(L=='U'):
    print("21")
elif(L=='V'):
    print("22")
elif(L=='W'):
    print("23")
elif(L=='X'):
    print("24")
elif(L=='Y'):
    print("25")
elif(L=='Z'):
    print("26")
